name: "Hello World Workflow"

# Trigger the workflow on push to master or production branches
on:
  push:
    branches:
      - master
      - production

jobs:
  hello_world:
    runs-on: windows-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"
