name: "Hello World workflow"

# Controls when the action will run. Triggers the workflow on push done to master or production branch.
on:
    push:
        branches:
            - master
            - production

jobs:
    hello_word:
        runs-on: window-latest
        steps:
            - name: "print hell world"
            run: echo "Hello World"