# name: "Multi event pipeline / workflow" # Nmae of the pipeline

# on:
#     push:  #Event : Whenever a push is made to the repository on the master branch
#         branches:
#             - master

# jobs:
#     on-push:
#         runs-on: window-latest
#         steps:
#             -name: "Running on master push"
#              run: echo "Running on master push"

    
# name: "Multi event pipeline / workflow" # Nmae of the pipeline

# on:
#   push: #Event : Whenever a push is made to the repository on the master branch
#     branches:
#       - master
#       - test

# jobs:
#   on-push: # jobs name
#     runs-on: windows-latest
#     steps: # Steps to be executed in the job
#       - name: "Running on master/test push"
#         run: echo "Running on master/test push"


# Without if :- both the request trigger on every commit
# name: "Multi event pipeline / workflow" # Nmae of the pipeline

# on:
#   push: #Event : Whenever a push is made to the repository on the master branch
#     branches:
#       - master
#       - test
#   pull_request: # Event trigger a pull request is made tothe repository
#     branches:
#       - master

# jobs:
#   on-push: # jobs name
#     runs-on: windows-latest
#     steps: # Steps to be executed in the job
#       - name: "Running on master/test push"
#         run: echo "Running on master/test push"

#   on-pull-request:
#     runs-on: window-latest
#     steps:
#         - name: "Running on pull request"
#           run: echo "Running on pull request"
      

# With if : Trigger when the condition matched 
name: "Multi event pipeline / workflow" # Nmae of the pipeline

on:
  push: #Event : Whenever a push is made to the repository on the master branch
    branches:
      - master
      - test
  pull_request: # Event trigger a pull request is made tothe repository
    branches:
      - master

jobs:
  on-push: # jobs name
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    steps: # Steps to be executed in the job
      - name: "Running on master/test push"
        run: echo "Running on master/test push"

  on-pull-request:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: window-latest
    steps:
        - name: "Running on pull request"
          run: echo "Running on pull request"
      